apiVersion: apps/v1
kind: Deployment
metadata:
  name: restappclima-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restappclima
  template:
    metadata:
      labels:
        app: restappclima
    spec:
      containers:
      - name: restappclima
        image: <registry>/restappclima:latest
        ports:
        - containerPort: 8080
