apiVersion: v1
kind: Service
metadata:
  name: savingsaccountapp-service
spec:
  type: LoadBalancer
  selector:
    app: savingsaccountapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
